# Generated by Django 6.0.1 on 2026-01-14 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_word",
                    models.CharField(
                        help_text="The word entered by user (French or English)",
                        max_length=200,
                    ),
                ),
                (
                    "french_word",
                    models.CharField(
                        help_text="French word in basic form", max_length=200
                    ),
                ),
                (
                    "english_translation",
                    models.TextField(help_text="English explanation/translation"),
                ),
                (
                    "french_explanation",
                    models.TextField(help_text="French explanation"),
                ),
                (
                    "english_examples",
                    models.TextField(
                        help_text="3 English usage examples (one per line)"
                    ),
                ),
                (
                    "french_examples",
                    models.TextField(
                        help_text="3 French usage examples (one per line)"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Difficulty level of the word",
                        max_length=20,
                    ),
                ),
                (
                    "familiarity",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("familiar", "Familiar"),
                            ("mastered", "Mastered"),
                        ],
                        default="new",
                        help_text="How familiar you are with this word",
                        max_length=20,
                    ),
                ),
                (
                    "openai_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The prompt used for OpenAI API",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Word",
                "verbose_name_plural": "Words",
                "ordering": ["-created_at"],
            },
        ),
    ]
