# Generated by Django 6.0.1 on 2026-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="cefr_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1 - Beginner"),
                    ("A2", "A2 - Elementary"),
                    ("B1", "B1 - Intermediate"),
                    ("B2", "B2 - Upper Intermediate"),
                    ("C1", "C1 - Advanced"),
                    ("C2", "C2 - Proficient"),
                ],
                help_text="CEFR level (A1, A2, B1, B2, C1, C2) as determined by Gemini",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                help_text="Deprecated: Use cefr_level instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="familiarity",
            field=models.IntegerField(
                default=1,
                help_text="Familiarity level from 1-5 (1 = new, 5 = mastered)",
            ),
        ),
    ]
