# Generated by Django 6.0.1 on 2026-01-14 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_word_cefr_level_alter_word_difficulty_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                        ],
                        help_text="User's French proficiency level (CEFR)",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "interest",
                    models.TextField(
                        blank=True,
                        help_text="User's interests or learning goals",
                        null=True,
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact information (email, phone, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Link to Django User model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
