# Generated by Django 6.0.1 on 2026-01-14 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title from RSS feed", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Article content")),
                (
                    "date",
                    models.DateTimeField(help_text="Publication date from RSS feed"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label or category for the article",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original URL of the article",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "rss_feed_url",
                    models.URLField(
                        blank=True,
                        help_text="RSS feed URL where this article was found",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["-date"], name="main_articl_date_713cfb_idx"),
                    models.Index(fields=["label"], name="main_articl_label_123e7c_idx"),
                ],
            },
        ),
    ]
