# Generated by Django 6.0.1 on 2026-01-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who saved this word",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
