# Generated by Django 6.0.1 on 2026-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_word_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="User's nickname or display name",
                max_length=100,
                null=True,
            ),
        ),
    ]
