# Generated by Django 6.0.1 on 2026-01-15 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userprofile_nickname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests_data",
            field=models.TextField(
                blank=True,
                default="{}",
                help_text="JSON data for weighted interest graph",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GlobalWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_index=True,
                        help_text="The word text (French or English)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr",
                        help_text="Language of the word (e.g., 'fr', 'en')",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Word",
                "verbose_name_plural": "Global Words",
                "ordering": ["text"],
                "indexes": [
                    models.Index(fields=["text"], name="main_global_text_8e8de8_idx"),
                    models.Index(
                        fields=["language", "text"],
                        name="main_global_languag_c262b1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        help_text="Gemini-generated definition/explanation"
                    ),
                ),
                (
                    "conversation",
                    models.TextField(
                        blank=True,
                        help_text="Personalized dialogue or conversation context",
                        null=True,
                    ),
                ),
                (
                    "examples",
                    models.TextField(
                        help_text="JSON-encoded examples (stored as text for SQLite compatibility)"
                    ),
                ),
                (
                    "target_cefr",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                        ],
                        help_text="Target CEFR level for this content",
                        max_length=2,
                    ),
                ),
                (
                    "interest_context",
                    models.CharField(
                        default="General",
                        help_text="Interest context (e.g., 'Hockey', 'Cooking', 'General')",
                        max_length=100,
                    ),
                ),
                (
                    "tone_style",
                    models.CharField(
                        default="Neutral",
                        help_text="Tone/style (e.g., 'Dark Humor', 'Academic', 'Neutral')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "word",
                    models.ForeignKey(
                        help_text="Reference to the global word",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_cards",
                        to="main.globalword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Card",
                "verbose_name_plural": "Content Cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "familiarity",
                    models.IntegerField(
                        default=1,
                        help_text="Familiarity level from 1-5 (1 = new, 5 = mastered)",
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        help_text="Content card for this word",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_vocabularies",
                        to="main.contentcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved this word",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Vocabulary",
                "verbose_name_plural": "User Vocabularies",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentcard",
            index=models.Index(
                fields=["word", "target_cefr", "interest_context", "tone_style"],
                name="main_conten_word_id_e5877c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentcard",
            unique_together={("word", "target_cefr", "interest_context", "tone_style")},
        ),
        migrations.AddIndex(
            model_name="uservocabulary",
            index=models.Index(
                fields=["user", "-added_at"], name="main_uservo_user_id_905173_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uservocabulary",
            unique_together={("user", "card")},
        ),
    ]
