# Generated by Django 6.0.1 on 2026-01-15 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_userprofile_interests_data_globalword_contentcard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Interest Category",
                "verbose_name_plural": "Interest Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="learning_goals",
            field=models.TextField(
                blank=True, help_text="Free-form learning goals and notes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interest",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED: Use interests (tags) instead. Kept for migration purposes.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tag name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this tag belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="main.interestcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest Tag",
                "verbose_name_plural": "Interest Tags",
                "ordering": ["category__order", "category__name", "order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "order"],
                        name="main_intere_categor_8e468d_idx",
                    )
                ],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's selected interest tags",
                related_name="users",
                to="main.interesttag",
            ),
        ),
    ]
