# Generated by Django 6.0.1 on 2026-01-15 18:29

from django.db import migrations


def migrate_interest_to_learning_goals(apps, schema_editor):
    """
    Data migration: Copy old interest field content to learning_goals.
    Preserves existing data without attempting to parse tags.
    """
    UserProfile = apps.get_model('main', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        if profile.interest and profile.interest.strip():
            # If learning_goals is empty, copy interest text
            if not profile.learning_goals or not profile.learning_goals.strip():
                profile.learning_goals = profile.interest
                profile.save(update_fields=['learning_goals'])
            # If learning_goals already has content, append the old interest
            else:
                profile.learning_goals = f"{profile.learning_goals}\n\n(Previous interests: {profile.interest})"
                profile.save(update_fields=['learning_goals'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Copy learning_goals back to interest (if needed).
    """
    UserProfile = apps.get_model('main', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        if profile.learning_goals and profile.learning_goals.strip():
            if not profile.interest or not profile.interest.strip():
                profile.interest = profile.learning_goals
                profile.save(update_fields=['interest'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_interestcategory_userprofile_learning_goals_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_interest_to_learning_goals,
            reverse_migration
        ),
    ]
