# Generated by Django 6.0.1 on 2026-01-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_migrate_interest_to_learning_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("early_childhood", "Early Childhood"),
                    ("early_elementary", "Early Elementary"),
                    ("upper_elementary", "Upper Elementary"),
                    ("middle_school", "Middle School"),
                    ("high_school", "High School"),
                    ("adult", "Adult"),
                    ("senior", "Senior"),
                ],
                help_text="User's age group or education level",
                max_length=20,
                null=True,
            ),
        ),
    ]
