# Generated by Django 6.0.1 on 2026-02-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_userprofile_age_group"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contentcard",
            name="main_conten_word_id_e5877c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="contentcard",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contentcard",
            name="target_language",
            field=models.CharField(
                default="fr",
                help_text="Target language for this content (e.g., 'fr', 'en', 'es')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="native_language",
            field=models.CharField(
                default="en",
                help_text="Language used for explanations/definitions (e.g., 'en', 'zh', 'fr')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_language",
            field=models.CharField(
                default="fr",
                help_text="Language the user is learning (e.g., 'fr', 'en', 'es')",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentcard",
            unique_together={
                (
                    "word",
                    "target_language",
                    "target_cefr",
                    "interest_context",
                    "tone_style",
                )
            },
        ),
        migrations.AddIndex(
            model_name="contentcard",
            index=models.Index(
                fields=[
                    "word",
                    "target_language",
                    "target_cefr",
                    "interest_context",
                    "tone_style",
                ],
                name="main_conten_word_id_24b65d_idx",
            ),
        ),
    ]
