# Generated by Django 6.0.1 on 2026-02-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_add_language_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="native_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("zh", "Chinese (Mandarin)"),
                    ("ja", "Japanese"),
                    ("fr", "French"),
                ],
                default="en",
                help_text="Language used for explanations/definitions",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("zh", "Chinese (Mandarin)"),
                    ("ja", "Japanese"),
                    ("fr", "French"),
                ],
                default="fr",
                help_text="Language the user is learning",
                max_length=10,
            ),
        ),
    ]
