# Generated by Django 6.0.1 on 2026-02-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_add_language_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
